### ISSUE TITLE
Question: Different Icons library.

### ISSUE THREAD

**Issue by awesomentw** [aw-studio/fjord#16]
Is it possible to use in $form->icon() different icon library. I would like to use 
https://www.npmjs.com/package/material-icons
or 
https://www.npmjs.com/package/@mdi/font

```
  $form->icon('icon')
                ->title(trans('app.icon'))

                ->icons([
                    '<i class="fas fa-address-book"></i>',
                    '<i class="fas fa-address-card"></i>',
                ])
                ->width(12);

```

**Comment by cbl** [comment]
Yes you can add css files to your Fjord application.

https://www.fjord-admin.com/docs/fields/icon/#add-your-own-icons

I noticed you are translating the title for your Icon field. You should use `__f` instead of `trans` to translate your Fjord backend, to use the locale that isset in **profile settings**. Here is explained why: https://www.fjord-admin.com/docs/basics/localization/

**Comment by cbl** [comment]
You can add this to your fjord.app config:
```php
'assets' => [
        // Set path to the root app.js and app.css file.
        'app' => [
            'js' => null,
            'css' => null,
        ],
        'css' => [
            // Include more css files here.
            'https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css',
        ],
],
```

Then you will be able to use material icons like so:
```php
$form->icon('icon')
          ->title('Icon')
          ->icons([
                '<i class="material-icons md-18">face</i>'
           ]);
```

**Comment by awesomentw** [comment]
Thank You. Works Amazing!
