### ISSUE TITLE
How to override views.

### ISSUE THREAD

**Issue by awesomentw** [aw-studio/fjord#18]
Hi, 
I would like to override views from /vendor/aw-studio/fjord/resources/views

when i use php `artisan vendor:publish --tag=views` im not getting what i need. 

is it possible?

**Comment by cbl** [comment]
That is not possible at the moment. What would you like to override?

**Comment by awesomentw** [comment]
Hi,
for example, i would like to:
- Change logo  on the login
- Add some additional info  on login page
- Change logo on app (left bar)
- Add some additional info in footer of app ( example Powered by: fjord )

**Comment by cbl** [comment]
Currently only scripts can be added to the login page. With this we have created the automatic login to our demo. You just have to pass a script variable to the View like so:
https://github.com/aw-studio/fjord-playground/blob/master/fjord/app/Composer/LoginComposer.php

We will discuss how and if we want to make login and logo extendable.

**Comment by lordjack** [comment]
> 
> 
> Hi, for example, i would like to:
> 
>     * Change logo  on the login
> 
>     * Add some additional info  on login page
> 
>     * Change logo on app (left bar)
> 
>     * Add some additional info in footer of app ( example Powered by: fjord )

Hello everyone, I have the same doubt, I want to change the logo. Anyone have any tips?

**Comment by nikolai-nikolajevic** [comment]
You can override it like every laravel vendor package with your own files in `resources/views/vendor/{package_name}`. So if you want to override the Logo on the login screen copy the view from `vendor/litstack/litstack/resources/views/auth/login.blade.php` to `resources/views/vendor/litstack/auth/login.blade.php` and make your changes there :)

but i would not recomend this, because litstack gets frequently updates and you would override new stuff
